title: <p align = "center"> Mohit Raj </p>
logo: /assets/img/MR.jpeg
description: 
<p align="center">
<a href="https://www.linkedin.com/in/raj-mohit/"LinkedIn<a/a>
<br>
</p>


theme: jekyll-theme-minimal
